name: EKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}




      - name: Build Docker Image
        run: |
          docker build -t bsreenu1999/crud .

      - name: Push Docker Image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username bsreenu1999 --password-stdin devops
          docker push devops/crud

      - name: Deploy to EKS
        run: |
          kubectl apply -f crud-k8s.yaml
